# Generated by Django 6.0.3 on 2026-03-11 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pendente', 'Pendente'), ('Pago', 'Pago'), ('Enviado', 'Enviado'), ('Cancelado', 'Cancelado'), ('Entregue', 'Entregue')], default='Pendente', max_length=20),
        ),
    ]
